config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'devise_custom/registrations' }

  resources :camping_groups do
    member do
      patch :pay_it
      patch :mark_exit
    end

    resources :vehicles, only: %i[new create]
    resources :people
  end

  root 'camping_groups#index'
end

app/models/person.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: people
#
#  id               :integer          not null, primary key
#  camping_group_id :integer          not null
#  document         :string
#  phone            :string
#  price_policy     :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  document_number  :string
#  full_name        :string           not null
#  courtesy         :boolean          default(FALSE)
#
# Foreign Keys
#
#  fk_rails_...  (camping_group_id => camping_groups.id)
#

class Person < ApplicationRecord
  belongs_to :camping_group, optional: true

  scope :billable, -> { where(courtesy: false) }

  validates :full_name, :document_number, presence: true
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < AuthenticatedController
  before_action :find_camping_group
  before_action :find_person, only: %i[edit update destroy]

  def new
    @person = Person.new(camping_group: @camping_group)
  end

  def create
    @person = Person.new(person_params.merge(camping_group: @camping_group))
    return redirect_to camping_group_path(@camping_group) if @person.save
    render :new
  end

  def edit; end

  def update
    if @person.update(person_params)
      redirect_to camping_group_path(@camping_group, notice: t('people.update.success'))
    else
      render :edit
    end
  end

  def destroy
    @person.delete
    redirect_to camping_group_path(@camping_group, notice: t('people.update.success'))
  end

  private

  def person_params
    params.require(:person).permit(:full_name, :document_number, :phone, :courtesy)
  end

  def find_camping_group
    @camping_group ||= CampingGroup.find(params[:camping_group_id])
  end

  def find_person
    @person = @camping_group.people.find(params[:id])
  end
end

app/views/people/_form.html.erb
<%= render 'person_fields', f: f %>

<div class="row">
  <div class="col-xs-6">
    <%= f.submit t('general.buttons.save'), class: 'btn btn-success' %>
  </div>
</div>

app/views/people/_person_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class='col-xs-12 form-group <%= 'has-error' if @person.errors['full_name'].present? %>'>
      <%= f.label :full_name, class: 'control-label' %>
      <%= f.text_field :full_name, autofocus: true, class: 'form-control' %>
      <span class="help-block"><%= @person.errors['full_name'].join(', ') %></span>
    </div>
  </div>

  <div class="row">
    <div class='col-xs-6 form-group <%= 'has-error' if @person.errors['document_number'].present? %>'>
      <%= f.label :document_number, class: 'control-label' %>
      <%= f.text_field :document_number, class: 'form-control' %>
      <span class="help-block"><%= @person.errors['document_number'].join(', ') %></span>
    </div>
    <div class='col-xs-6 form-group <%= 'has-error' if @person.errors['phone'].present? %>'>
      <%= f.label :phone, class: 'control-label' %>
      <%= f.text_field :phone, class: 'form-control' %>
      <span class="help-block"><%= @person.errors['phone'].join(', ') %></span>
    </div>
  </div>

  <div class="row">
    <div class='col-xs-6 form-check botton-spaced-component'>
      <%= f.check_box :courtesy, class: 'form-check-input', checked: nil %>
      <%= f.label :courtesy, class: 'form-check-label' %>
    </div>
  </div>
</div>

app/views/people/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 swarga-header">
      <ul class="breadcrumb">
        <li><%= link_to CampingGroup.model_name.human(count: 2), camping_groups_path %></li>
        <li><%= link_to "#{CampingGroup.model_name.human} (#{@camping_group.tent_numbers.join(', ')})", camping_group_path(@camping_group) %></li>
        <li><%= t('people.edit.title') %></li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 swarga-header">
      <%= form_for @person, url: camping_group_person_path(@camping_group, @person) do |f| %>
        <%= render 'form', f: f %>
      <% end %>
    </div>
  </div>
</div>

app/views/people/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <ul class="breadcrumb">
        <li><%= link_to CampingGroup.model_name.human(count: 2), camping_groups_path %></li>
        <li><%= link_to "#{CampingGroup.model_name.human} (#{@camping_group.tent_numbers.join(', ')})", camping_group_path(@camping_group) %></li>
        <li><%= t('people.new.title') %></li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 swarga-header">
      <%= form_for @person, url: camping_group_people_path(@camping_group) do |f| %>
        <%= render 'form', f: f %>
      <% end %>
    </div>
  </div>
</div>