config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'devise_custom/registrations' }

  resources :camping_groups do
    member do
      patch :pay_it
      patch :mark_exit
    end

    resources :vehicles, only: %i[new create]
    resources :people
  end

  root 'camping_groups#index'
end

app/models/camping_group.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: camping_groups
#
#  created_at       :datetime         not null
#  end_date         :date             not null
#  id               :integer          not null, primary key
#  price_per_person :decimal(, )
#  price_total      :decimal(, )
#  start_date       :date             not null
#  status           :integer          default("reserved"), not null
#  tent_numbers     :integer          not null, is an Array
#  updated_at       :datetime         not null
#

class CampingGroup < ApplicationRecord
  enum status: { reserved: 0, paid: 1, left: 2 }

  has_many :people, dependent: :restrict_with_exception
  accepts_nested_attributes_for :people, reject_if: :all_blank

  has_many :vehicles, dependent: :restrict_with_exception
  accepts_nested_attributes_for :vehicles, reject_if: :all_blank

  scope :reserved_active, -> { reserved.where('end_date > ?', Time.zone.today).order(:end_date) }
  scope :paid_active, -> { paid.where('end_date > ?', Time.zone.today).order(:end_date) }
  scope :leaving, -> { where('end_date <= ? AND camping_groups.status <> ?', Time.zone.today, CampingGroup.statuses[:left]).order(:end_date, :start_date) }
  scope :for_term, ->(term) { includes(:people).where('(UPPER(full_name) LIKE :search_name) OR (:search_tent = ANY(tent_numbers))', search_name: "%#{term&.upcase}%", search_tent: term.to_i).references(:people) }

  validates :tent_numbers, :start_date, :end_date, presence: true
  validate :some_price_present?

  def unpaid_leaving?
    reserved? && end_date <= Time.zone.today
  end

  def calculated_total
    return (price_per_person * people.billable.count) * qty_nights if price_per_person.present?
    price_total
  end

  def qty_people
    people.count
  end

  def qty_nights
    (end_date - start_date).to_i
  end

  private

  def some_price_present?
    return true if price_total.present? || price_per_person.present?
    errors.add(:price_total, I18n.t('camping_group.validations.no_price'))
    errors.add(:price_per_person, I18n.t('camping_group.validations.no_price'))
  end
end

app/controllers/camping_groups_controller.rb
# frozen_string_literal: true

class CampingGroupsController < AuthenticatedController
  before_action :find_camping_group, except: %i[index new create]

  def index
    @last_day_camping_groups = CampingGroup.leaving
    @reserved_camping_groups = CampingGroup.reserved_active
    @paid_camping_groups = CampingGroup.paid_active
    @left_camping_groups = CampingGroup.left.order(end_date: :desc)

    perform_search if search_term.present?

    render :index
  end

  def new
    @camping_group = CampingGroup.new
    build_camping_group
  end

  def create
    @camping_group = CampingGroup.new(camping_group_params.merge(tent_numbers: tent_numbers))
    return redirect_to camping_group_path(@camping_group) if @camping_group.save
    build_camping_group
    render :new
  end

  def pay_it
    @camping_group.paid!
    redirect_to camping_groups_path, notice: t('camping_groups.pay_it.success.message')
  end

  def find_camping_group
    @camping_group = CampingGroup.find(params[:id])
  end

  def mark_exit
    @camping_group.left!
    redirect_to camping_groups_path, notice: t('camping_groups.mark_exit.success.message')
  end

  def update
    @camping_group.update(camping_group_params.merge(tent_numbers: tent_numbers))
    return redirect_to camping_groups_path if @camping_group.save
    render :edit
  end

  private

  def build_camping_group
    @camping_group.people.build if @camping_group.people.blank?
    @person ||= @camping_group.people.last
    @camping_group.vehicles.build if @camping_group.vehicles.blank?
    @new_vehicle ||= @camping_group.vehicles.last
    @new_vehicle.vehicle_type = nil
  end

  def camping_group_params
    params.require(:camping_group).permit(:tent_numbers, :price_per_person, :price_total, :start_date, :end_date, people_attributes: %i[full_name document_number phone courtesy], vehicles_attributes: %i[license_plate vehicle_type])
  end

  def tent_numbers
    camping_group_params[:tent_numbers].split(',')
  end

  def perform_search
    @last_day_camping_groups = @last_day_camping_groups.for_term(search_term) if search_term.present?
    @reserved_camping_groups = @reserved_camping_groups.for_term(search_term) if search_term.present?
    @paid_camping_groups = @paid_camping_groups.for_term(search_term) if search_term.present?
  end

  def search_term
    @search_term ||= params[:search_term]
  end
end

app/views/camping_groups/_camping_groups_list.html.erb
<div class="row">
  <div class="col-xs-12 swarga-header">
    <h4><%= list_title %></h4>
    <% if camping_groups.empty? %>
        <span class="no-data"><%= t('camping_groups.index.empty_message') %></span>
    <% else %>
        <table class="table">
          <th><%= CampingGroup.human_attribute_name(:tent_numbers) %></th>
          <th><%= CampingGroup.human_attribute_name(:status) %></th>
          <th><%= t('camping_groups.index.people') %></th>
          <th><%= CampingGroup.human_attribute_name(:price_total) %></th>
          <th><%= CampingGroup.human_attribute_name(:end_date) %></th>
          <th><%= t('camping_groups.index.nights') %></th>
          <th>#</th>
          <tbody>
          <% camping_groups.each do |camping_group| %>
              <tr class='<%= 'not-paid-leaving' if camping_group.unpaid_leaving? %>'>
                <td><%= link_to camping_group.tent_numbers.join(', '), camping_group_path(camping_group) %></td>

                <td><%= t("activerecord.attributes.camping_group.enum.status.#{camping_group.status}") %></td>
                <td><%= camping_group.people.pluck(:full_name).join(', ') %></td>
                <td><%= number_to_currency(camping_group.calculated_total) %></td>
                <td><%= l(camping_group.end_date) %></td>
                <td><%= camping_group.qty_nights %></td>
                <td>
                  <%= link_to edit_camping_group_path(camping_group) do %>
                      <i class="fa fa-pencil"></i>
                  <% end %>
                  <%= link_to camping_group_path(camping_group) do %>
                      <i class="fa fa-eye"></i>
                  <% end %>
                  <% if camping_group.reserved? %>
                      <%= link_to pay_it_camping_group_path(camping_group), method: :patch do %>
                          <i class="fa fa-credit-card"></i>
                      <% end %>
                  <% end %>
                  <% unless camping_group.left? %>
                      <%= link_to mark_exit_camping_group_path(camping_group), method: :patch do %>
                          <i class="fa fa-power-off"></i>
                      <% end %>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
          <tfoot>
            <%= "Valor total: #{number_to_currency(camping_groups.sum(&:calculated_total))}" %>
          </tfoot>
        </table>
    <% end %>
  </div>
</div>

app/views/camping_groups/_form.html.erb
<div class="list-table">
  <h2><%= t('camping_groups.new.main_form.title') %></h2>

  <div class="row">
    <div class='col-xs-4 form-group <%= 'has-error' if @camping_group.errors[:tent_numbers].present? %>'>
      <%= f.label :tent_numbers, class: 'control-label' %>
      <%= f.text_field :tent_numbers, value: @camping_group.tent_numbers&.join(','), autofocus: true, class: 'form-control' %>
      <span class="help-block"><%= @camping_group.errors[:tent_numbers].join(', ') %></span>
    </div>

    <div class='col-xs-4 form-group <%= 'has-error' if @camping_group.errors[:start_date].present? %>'>
      <%= f.label :start_date, class: 'control-label' %>
      <%= f.date_field :start_date, class: 'form-control' %>
      <span class="help-block"><%= @camping_group.errors[:start_date].join(', ') %></span>
    </div>

    <div class='col-xs-4 form-group <%= 'has-error' if @camping_group.errors[:end_date].present? %>'>
      <%= f.label :end_date, class: 'control-label' %>
      <%= f.date_field :end_date, class: 'form-control' %>
      <span class="help-block"><%= @camping_group.errors[:end_date].join(', ') %></span>
    </div>
  </div>

  <div class="row">
    <div class='col-xs-6 form-group <%= 'has-error' if @camping_group.errors[:price_per_person].present? %>'>
      <%= f.label :price_per_person, class: 'control-label' %>
      <%= f.text_field :price_per_person, class: 'form-control' %>
      <span class="help-block"><%= @camping_group.errors[:price_per_person].join(', ') %></span>
    </div>

    <div class='col-xs-6 form-group <%= 'has-error' if @camping_group.errors[:price_total].present? %>'>
      <%= f.label :price_total, class: 'control-label' %>
      <%= f.text_field :price_total, class: 'form-control' %>
      <span class="help-block"><%= @camping_group.errors[:price_total].join(', ') %></span>
    </div>
  </div>
</div>

<% unless @camping_group.persisted? %>
  <div class="list-table">
    <h2><%= t('people.index.title') %></h2>

    <%= f.fields_for :people do |form_person| %>
      <%= render 'people/person_fields', f: form_person %>
    <% end %>
  </div>

  <div class="list-table">
    <h2><%= t('vehicles.index.title') %></h2>

    <%= f.fields_for :vehicles do |form_vehicle| %>
      <%= render 'vehicles/vehicle_fields', f: form_vehicle %>
    <% end %>
  </div>
<% end %>

app/views/camping_groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 swarga-header">
      <h1><%= t('camping_groups.edit.title') %></h1>
    </div>
  </div>

  <%= form_for @camping_group, url: camping_group_path(@camping_group), method: :put do |f| %>
      <div class="row">
        <div class="col-xs-10 col-xs-offset-1 swarga-header">
          <h2><%= t('camping_groups.new.main_form.title') %></h2>
          <%= render 'form', f: f %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      </div>
  <% end %>
</div>

app/views/camping_groups/index.html.erb
<div class="container">
  <div class="row botton-spaced-component">
    <%= form_tag camping_groups_path, method: :get, class: 'form-group' do %>
      <span class="col-xs-5">
        <%= text_field_tag :search_term, params[:search_term], placeholder: t('edit.search.placeholder'), class: 'col-xs-5 form-control' %>
      </span>
      <span class="col-xs-2">
        <%= submit_tag t('general.search'), class: 'btn btn-primary' %>
      </span>
      <span class="col-xs-5">
        <%= link_to t('camping_groups.new.title'), new_camping_group_path, class: 'btn btn-sm btn-primary botton-spaced-component pull-right' %>
      </span>
    <% end %>
  </div>

  <div class="list-table">
    <%= render 'camping_groups_list', camping_groups: @last_day_camping_groups, list_title: t('camping_groups.index.leaving_today.title', value: @last_day_camping_groups.size) %>
  </div>

  <div class="list-table">
    <%= render 'camping_groups_list', camping_groups: @reserved_camping_groups, list_title: t('camping_groups.index.reserved.title', value: @reserved_camping_groups.size) %>
  </div>

  <div class="list-table">
    <%= render 'camping_groups_list', camping_groups: @paid_camping_groups, list_title: t('camping_groups.index.paid.title', value: @paid_camping_groups.size) %>
  </div>

  <div class="list-table">
    <%= render 'camping_groups_list', camping_groups: @left_camping_groups, list_title: t('camping_groups.index.left.title', value: @left_camping_groups.size) %>
  </div>
</div>

app/views/camping_groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <ul class="breadcrumb">
        <li><%= link_to CampingGroup.model_name.human(count: 2), camping_groups_path %></li>
        <li><%= t('camping_groups.new.title') %></li>
      </ul>
    </div>
  </div>

  <%= form_for @camping_group do |f| %>
    <div class="row">
      <div class="col-xs-12">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </div>

    <div class="row botton-spaced-component">
      <div class="col-xs-12">
        <%= render 'form', f: f %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/camping_groups/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 swarga-header">
      <ul class="breadcrumb">
        <li><%= link_to CampingGroup.model_name.human(count: 2), camping_groups_path %></li>
        <li><%= t('camping_groups.show.title') %></li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 swarga-subtitle">
      <span class="col-xs-3 stamp"><%= "#{CampingGroup.human_attribute_name(:tent_numbers, count: 1)}: #{@camping_group.tent_numbers.join(', ')}"%></span>
      <span class="col-xs-2 stamp"><%= "#{CampingGroup.human_attribute_name(:start_date)}: #{l(@camping_group.start_date)}"%></span>
      <span class="col-xs-2 stamp"><%= "#{CampingGroup.human_attribute_name(:end_date)}: #{l(@camping_group.end_date)}"%></span>
      <span class="col-xs-2 stamp"><%= "#{CampingGroup.human_attribute_name(:price_per_person)}: #{number_to_currency(@camping_group.price_per_person)}"%></span>
      <span class="col-xs-2 stamp"><%= "#{CampingGroup.human_attribute_name(:price_total)}: #{number_to_currency(@camping_group.calculated_total)}"%></span>
    </div>
  </div>


  <div class="row">
    <div class="col-xs-12">
      <h2><%= t('people.index.title') %></h2>
      <table class="table">
        <th><%= Person.human_attribute_name(:full_name) %></th>
        <th><%= Person.human_attribute_name(:document_number) %></th>
        <th><%= Person.human_attribute_name(:phone) %></th>
        <th>#</th>
        <tbody>
        <% @camping_group.people.each do |person| %>
          <tr>
            <td><%= person.full_name %></td>
            <td><%= person.document_number %></td>
            <td><%= person.phone %></td>
            <td>
              <%= link_to edit_camping_group_person_path(@camping_group, person) do %>
                <i class="fa fa-pencil"></i>
              <% end %>
              <%= link_to camping_group_person_path(@camping_group, person), method: :delete do %>
                <i class="fa fa-remove"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to t('people.new.title'), new_camping_group_person_path(@camping_group), class: 'btn btn-sm btn-primary' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <h2><%= t('vehicles.index.title') %></h2>
      <table class="table">
        <th><%= Vehicle.human_attribute_name(:license_plate) %></th>
        <th><%= Vehicle.human_attribute_name(:vehicle_type) %></th>
        <tbody>
        <% @camping_group.vehicles.each do |vehicle| %>
          <tr>
            <td><%= vehicle.license_plate %></td>
            <td><%= t("activerecord.attributes.vehicle.enums.vehicle_types.#{vehicle.vehicle_type}") %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to t('vehicles.new.title'), new_camping_group_vehicle_path(@camping_group), class: 'btn btn-sm btn-primary' %>
    </div>
  </div>
</div>