config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'devise_custom/registrations' }

  resources :camping_groups do
    member do
      patch :pay_it
      patch :mark_exit
    end

    resources :vehicles, only: %i[new create]
    resources :people
  end

  root 'camping_groups#index'
end

app/models/vehicle.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: vehicles
#
#  camping_group_id :integer          not null
#  created_at       :datetime         not null
#  id               :integer          not null, primary key
#  license_plate    :string           not null
#  updated_at       :datetime         not null
#  vehicle_type     :integer          default("car"), not null
#
# Foreign Keys
#
#  fk_rails_...  (camping_group_id => camping_groups.id)
#

class Vehicle < ApplicationRecord
  belongs_to :camping_group

  validates :license_plate, :vehicle_type, :camping_group, presence: true

  enum vehicle_type: { car: 0, moto: 1, motor_home: 2 }
end

app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < AuthenticatedController
  before_action :find_camping_group

  def new
    @new_vehicle = Vehicle.new(camping_group: @camping_group)
  end

  def create
    @new_vehicle = Vehicle.new(vehicle_params.merge(camping_group: @camping_group))
    return redirect_to camping_group_path(@camping_group) if @new_vehicle.save
    render :new
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:license_plate, :vehicle_type)
  end

  def find_camping_group
    @camping_group ||= CampingGroup.find(params[:camping_group_id])
  end
end

app/views/vehicles/_form.html.erb
<%= form_for @new_vehicle, url: camping_group_vehicles_path(@camping_group) do |f| %>
    <%= render 'vehicle_fields', f: f %>

    <div class="row">
      <div class="col-xs-6">
        <%= f.submit t('general.buttons.save'), class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/vehicles/_vehicle_fields.html.erb
<div class="row">
  <div class='col-xs-12'>
    <div class="row">
      <div class='col-xs-12 form-group'>
        <%= f.label :vehicle_type, class: 'control-label' %>
        <%= f.select :vehicle_type, Vehicle.vehicle_types.map { |key, _value| [t("activerecord.attributes.vehicle.enums.vehicle_types.#{key}"), key] }, { include_blank: 'Selecione um tipo', selected: @new_vehicle.vehicle_type }, class: 'form-control' %>
      </div>
    </div>

    <div class="row">
      <div class='col-xs-12 form-group <%= 'has-error' if @new_vehicle.errors[:license_plate].present? %>'>
        <%= f.label :license_plate, class: 'control-label' %>
        <%= f.text_field :license_plate, autofocus: true, class: 'form-control' %>
        <span class="help-block"><%= @new_vehicle.errors[:license_plate].join(', ') %></span>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <ul class="breadcrumb">
        <li><%= link_to CampingGroup.model_name.human(count: 2), camping_groups_path %></li>
        <li><%= link_to "#{CampingGroup.model_name.human} (#{@camping_group.tent_numbers.join(', ')})", camping_group_path(@camping_group) %></li>
        <li><%= t('vehicles.new.title') %></li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= render 'form' %>
    </div>
  </div>
</div>